# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SCmain.ui'
#
# Created: Thu Sep  5 11:00:21 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(604, 522)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.AllSurveys = QtGui.QCheckBox(Dialog)
        self.AllSurveys.setGeometry(QtCore.QRect(20, 290, 141, 41))
        self.AllSurveys.setStyleSheet(_fromUtf8("font: 12pt \"MS Shell Dlg 2\";"))
        self.AllSurveys.setObjectName(_fromUtf8("AllSurveys"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 90, 241, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(330, 0, 241, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.NumberBootstrapLabel = QtGui.QLabel(Dialog)
        self.NumberBootstrapLabel.setGeometry(QtCore.QRect(430, 300, 131, 41))
        self.NumberBootstrapLabel.setWordWrap(True)
        self.NumberBootstrapLabel.setObjectName(_fromUtf8("NumberBootstrapLabel"))
        self.NumberBootstrap = QtGui.QPlainTextEdit(Dialog)
        self.NumberBootstrap.setGeometry(QtCore.QRect(320, 300, 101, 31))
        self.NumberBootstrap.setObjectName(_fromUtf8("NumberBootstrap"))
        self.RandomSeed = QtGui.QPlainTextEdit(Dialog)
        self.RandomSeed.setGeometry(QtCore.QRect(320, 350, 101, 31))
        self.RandomSeed.setObjectName(_fromUtf8("RandomSeed"))
        self.RandomSeedLabel = QtGui.QLabel(Dialog)
        self.RandomSeedLabel.setGeometry(QtCore.QRect(430, 350, 131, 31))
        self.RandomSeedLabel.setObjectName(_fromUtf8("RandomSeedLabel"))
        self.AvailSurveys = QtGui.QListWidget(Dialog)
        self.AvailSurveys.setGeometry(QtCore.QRect(21, 121, 251, 161))
        self.AvailSurveys.setObjectName(_fromUtf8("AvailSurveys"))
        self.TransectCharacteristics = QtGui.QListWidget(Dialog)
        self.TransectCharacteristics.setGeometry(QtCore.QRect(320, 31, 256, 91))
        self.TransectCharacteristics.setObjectName(_fromUtf8("TransectCharacteristics"))
        self.DoCalcs = QtGui.QPushButton(Dialog)
        self.DoCalcs.setGeometry(QtCore.QRect(20, 440, 91, 41))
        self.DoCalcs.setObjectName(_fromUtf8("DoCalcs"))
        self.QuitBttn = QtGui.QPushButton(Dialog)
        self.QuitBttn.setGeometry(QtCore.QRect(150, 440, 91, 41))
        self.QuitBttn.setObjectName(_fromUtf8("QuitBttn"))
        self.MinDepthLabel = QtGui.QLabel(Dialog)
        self.MinDepthLabel.setGeometry(QtCore.QRect(130, 340, 131, 31))
        self.MinDepthLabel.setWordWrap(True)
        self.MinDepthLabel.setObjectName(_fromUtf8("MinDepthLabel"))
        self.MinDepth = QtGui.QPlainTextEdit(Dialog)
        self.MinDepth.setGeometry(QtCore.QRect(20, 340, 101, 31))
        self.MinDepth.setObjectName(_fromUtf8("MinDepth"))
        self.MaxDepth = QtGui.QPlainTextEdit(Dialog)
        self.MaxDepth.setGeometry(QtCore.QRect(20, 390, 101, 31))
        self.MaxDepth.setObjectName(_fromUtf8("MaxDepth"))
        self.MaxDepthLabel = QtGui.QLabel(Dialog)
        self.MaxDepthLabel.setGeometry(QtCore.QRect(130, 390, 131, 31))
        self.MaxDepthLabel.setWordWrap(True)
        self.MaxDepthLabel.setObjectName(_fromUtf8("MaxDepthLabel"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 150, 171, 101))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.LogbookData = QtGui.QRadioButton(self.groupBox_2)
        self.LogbookData.setGeometry(QtCore.QRect(10, 10, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LogbookData.setFont(font)
        self.LogbookData.setAutoExclusive(True)
        self.LogbookData.setObjectName(_fromUtf8("LogbookData"))
        self.MarketSample = QtGui.QRadioButton(self.groupBox_2)
        self.MarketSample.setGeometry(QtCore.QRect(10, 40, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MarketSample.setFont(font)
        self.MarketSample.setAutoExclusive(True)
        self.MarketSample.setObjectName(_fromUtf8("MarketSample"))
        self.Biodata = QtGui.QRadioButton(self.groupBox_2)
        self.Biodata.setGeometry(QtCore.QRect(10, 70, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Biodata.setFont(font)
        self.Biodata.setAutoExclusive(True)
        self.Biodata.setObjectName(_fromUtf8("Biodata"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(320, 390, 241, 111))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.californicus = QtGui.QRadioButton(self.groupBox_3)
        self.californicus.setGeometry(QtCore.QRect(10, 20, 211, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.californicus.setFont(font)
        self.californicus.setAutoExclusive(True)
        self.californicus.setObjectName(_fromUtf8("californicus"))
        self.miniata = QtGui.QRadioButton(self.groupBox_3)
        self.miniata.setGeometry(QtCore.QRect(10, 50, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.miniata.setFont(font)
        self.miniata.setAutoExclusive(True)
        self.miniata.setObjectName(_fromUtf8("miniata"))
        self.pallida = QtGui.QRadioButton(self.groupBox_3)
        self.pallida.setGeometry(QtCore.QRect(10, 80, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pallida.setFont(font)
        self.pallida.setAutoExclusive(True)
        self.pallida.setObjectName(_fromUtf8("pallida"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 0, 241, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.RunComments = QtGui.QPlainTextEdit(Dialog)
        self.RunComments.setGeometry(QtCore.QRect(20, 30, 251, 51))
        self.RunComments.setObjectName(_fromUtf8("RunComments"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Sea Cucumber Analysis Program", None))
        self.AllSurveys.setText(_translate("Dialog", "Do All Projects?", None))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Available Projects</p></body></html>", None))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Transect Characteristics</span></p></body></html>", None))
        self.NumberBootstrapLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Number of Bootstrap Repititions</span></p></body></html>", None))
        self.RandomSeedLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Random Seed</span></p></body></html>", None))
        self.DoCalcs.setText(_translate("Dialog", "Do\n"
"Calculations", None))
        self.QuitBttn.setText(_translate("Dialog", "Quit", None))
        self.MinDepthLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Minimum Depth (m)</span></p></body></html>", None))
        self.MaxDepthLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Maximum Depth (m)</span></p></body></html>", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Source of Mean Weight Estimates", None))
        self.LogbookData.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\"><br/></span></p></body></html>", None))
        self.LogbookData.setText(_translate("Dialog", "Logbook data", None))
        self.MarketSample.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\"><br/></span></p></body></html>", None))
        self.MarketSample.setText(_translate("Dialog", "Market Sample", None))
        self.Biodata.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\"><br/></span></p></body></html>", None))
        self.Biodata.setText(_translate("Dialog", "Biodata in Database", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Species", None))
        self.californicus.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\"><br/></span></p></body></html>", None))
        self.californicus.setText(_translate("Dialog", "californicus(commercial)", None))
        self.miniata.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\"><br/></span></p></body></html>", None))
        self.miniata.setText(_translate("Dialog", "miniata", None))
        self.pallida.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\"><br/></span></p></body></html>", None))
        self.pallida.setText(_translate("Dialog", "pallida ", None))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Run Comments</p></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

