'''A library of suffixes to indicate physical units'''
Metres='_metres'
PerMetre='_PerMetre'
PerMetreSquared='_PerMetreSquared'
KgPerMetre='_KgPerMetre'
KgPerMetreSquared='_KgPerMetreSquared'
Mm='_Mm'
MetresSquared='_MetresSquared'
Metres='_Metres'
Kilograms='_Kilograms'
